version: '3'
  
services:
  api:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: api
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3307:3306
    volumes:
      - ./../.docker/mysql:/var/lib/mysql
    container_name: mysql